name: Employment_Service
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/black/
    - assets/icons/white/
    - assets/images/main_page_pic.jpg
    - assets/icons/default_icon.png

  fonts:
    - family: Overpass
      fonts: 
       - asset: assets/fonts/Overpass-VariableFont_wght.ttf

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/icons/default_icon.png"
